"""
HHS OCR Breach Portal Client — HIPAA breach records affecting 500+ patients.

Data source: HHS Office for Civil Rights Breach Portal
  - URL: https://ocrportal.hhs.gov/ocr/breach/breach_report.jsf
  - Access method: JSF form navigation + HTML table scraping
  - No API: The portal is a Java Server Faces (PrimeFaces 12.x) application.
    Data is served via server-side rendered HTML tables. Navigation requires
    JSF ViewState tokens and POST requests to follow command links.
  - No authentication required. Public dataset.

Navigation flow:
  1. GET breach_frontpage.jsf → obtain JSESSIONID cookie + ViewState
  2. POST with ocrForm:j_idt39 → 302 redirect to breach_report_hip.jsf
  3. GET breach_report_hip.jsf → HTML table with 50 breach records/page

Table columns: Name of Covered Entity, State, Covered Entity Type,
  Individuals Affected, Breach Submission Date, Type of Breach,
  Location of Breached Information, Business Associate Present, Web Description

Fragility points:
  1. JSF ViewState: The ViewState token changes per session. We must obtain
     a fresh one for each navigation sequence.
  2. Session cookies: JSESSIONID is required for the multi-step navigation.
  3. Pagination: Only 50 records per page. Searching for a specific entity
     requires scanning all visible rows. The portal has no search form —
     we filter client-side from the default result set.
  4. Data completeness: Only breaches affecting 500+ individuals are listed.
     Smaller breaches exist but are not publicly reported.
  5. Rate limiting: No documented limits, but be polite with single-session access.
  6. JSF component IDs: Form field names like j_idt39 may change if the
     portal is updated. These are auto-generated by JSF.

Extraction: Deterministic HTML parsing + Claude Haiku per CLAUDE.md model assignment.
Cache TTL: 30 days (breach data is historical and rarely updated retroactively).
"""

import json
import os
import re
import sys
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path

import requests
import yaml

try:
    import anthropic
except ImportError:
    anthropic = None

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SOURCES_DIR = PROJECT_ROOT / "sources"
PERSONA_PATH = PROJECT_ROOT / "persona" / "verkada-se.yml"

HAIKU_MODEL = "claude-haiku-4-5-20251001"
CACHE_TTL_DAYS = 30

HHS_BASE = "https://ocrportal.hhs.gov/ocr/breach"
HHS_FRONTPAGE = f"{HHS_BASE}/breach_frontpage.jsf"
HHS_REPORT = f"{HHS_BASE}/breach_report_hip.jsf"

UA = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"

BREACH_TYPE_SIGNALS = {
    "Hacking/IT Incident": "cyber_breach",
    "Unauthorized Access/Disclosure": "unauthorized_access",
    "Theft": "physical_theft",
    "Loss": "device_loss",
    "Improper Disposal": "disposal_failure",
}


# ---------------------------------------------------------------------------
# Persona
# ---------------------------------------------------------------------------

def _load_persona() -> dict:
    if not PERSONA_PATH.exists():
        return {}
    try:
        return yaml.safe_load(PERSONA_PATH.read_text()) or {}
    except Exception:
        return {}


# ---------------------------------------------------------------------------
# JSF Navigation
# ---------------------------------------------------------------------------

def _create_session() -> requests.Session:
    s = requests.Session()
    s.headers.update({"User-Agent": UA})
    return s


def _get_viewstate(html: str) -> str | None:
    match = re.search(r'javax\.faces\.ViewState[^>]*value="([^"]+)"', html)
    return match.group(1) if match else None


def fetch_breach_page(session: requests.Session) -> str | None:
    """Navigate JSF app to reach breach report listing page."""
    # Step 1: Get frontpage with ViewState
    resp = session.get(HHS_FRONTPAGE, timeout=30)
    if resp.status_code != 200:
        print(f"  [hhs] frontpage returned {resp.status_code}", file=sys.stderr)
        return None

    viewstate = _get_viewstate(resp.text)
    if not viewstate:
        print(f"  [hhs] no ViewState found on frontpage", file=sys.stderr)
        return None

    # Step 2: POST to navigate to HIPAA breach reports
    data = {
        "ocrForm": "ocrForm",
        "ocrForm:j_idt39": "ocrForm:j_idt39",
        "javax.faces.ViewState": viewstate,
    }
    resp = session.post(HHS_FRONTPAGE, data=data, timeout=30, allow_redirects=False)

    if resp.status_code not in (302, 303):
        print(f"  [hhs] navigation POST returned {resp.status_code}", file=sys.stderr)
        return None

    # Step 3: Follow redirect to breach report page
    redirect_url = resp.headers.get("Location", "")
    if not redirect_url.startswith("http"):
        redirect_url = f"{HHS_BASE}/{redirect_url.lstrip('/')}"

    resp = session.get(redirect_url, timeout=30)
    if resp.status_code != 200:
        # Try the known URL directly
        resp = session.get(HHS_REPORT, timeout=30)

    if resp.status_code != 200:
        print(f"  [hhs] breach report page returned {resp.status_code}", file=sys.stderr)
        return None

    return resp.text


# ---------------------------------------------------------------------------
# HTML Parsing
# ---------------------------------------------------------------------------

def parse_breach_table(html: str) -> list[dict]:
    """Parse the PrimeFaces DataTable of breach records."""
    records = []

    rows = re.findall(r'<tr[^>]*data-ri[^>]*>(.*?)</tr>', html, re.S)

    for row in rows:
        cells = re.findall(r'<td[^>]*>(.*?)</td>', row, re.S)
        if len(cells) < 9:
            continue

        record = {
            "entity_name": _clean(cells[1]),
            "state": _clean(cells[2]),
            "entity_type": _clean(cells[3]),
            "individuals_affected": _parse_int(_clean(cells[4])),
            "breach_submission_date": _clean(cells[5]),
            "breach_type": _clean(cells[6]),
            "location_of_breach": _clean(cells[7]),
            "business_associate": _clean(cells[8]),
        }

        # Try to extract web description from expanded row
        desc_match = re.search(
            r'<div[^>]*class="[^"]*row-expansion[^"]*"[^>]*>(.*?)</div>',
            row, re.S
        )
        if desc_match:
            record["description"] = _clean(desc_match.group(1))

        records.append(record)

    return records


def _clean(html_text: str) -> str:
    return re.sub(r'<[^>]+>', '', html_text).strip()


def _parse_int(s: str) -> int:
    try:
        return int(s.replace(",", ""))
    except (ValueError, AttributeError):
        return 0


# ---------------------------------------------------------------------------
# Entity matching
# ---------------------------------------------------------------------------

def filter_by_entity(records: list[dict], entity_name: str) -> list[dict]:
    """Filter breach records matching an entity name (fuzzy)."""
    entity_lower = entity_name.lower()
    tokens = entity_lower.split()

    exact = []
    partial = []

    for rec in records:
        name_lower = rec["entity_name"].lower()

        if entity_lower in name_lower or name_lower in entity_lower:
            exact.append(rec)
        elif all(t in name_lower for t in tokens if len(t) > 2):
            partial.append(rec)

    return exact if exact else partial


# ---------------------------------------------------------------------------
# Haiku analysis
# ---------------------------------------------------------------------------

def analyze_with_haiku(records: list[dict], entity_name: str, persona: dict) -> dict:
    if not anthropic or not os.environ.get("ANTHROPIC_API_KEY"):
        return {"status": "skipped", "reason": "ANTHROPIC_API_KEY not set"}

    if not records:
        return {"status": "no_breaches"}

    triggers = persona.get("triggers", [])
    trigger_names = [t.get("name", "") for t in triggers if isinstance(t, dict)]

    prompt = f"""Analyze these HIPAA breach records for "{entity_name}" for pre-sales security intelligence.

BREACH RECORDS:
{json.dumps(records, indent=2)}

TRIGGERS from persona: {', '.join(trigger_names)}

Determine:
1. Which breach types indicate physical security gaps vs. cyber gaps
2. Whether breach patterns suggest need for access control, cameras, or visitor management
3. Which triggers from the persona file fire based on this breach history
4. Overall risk posture and urgency for the entity

Return JSON:
{{
  "physical_security_gaps": ["..."],
  "cyber_gaps": ["..."],
  "verkada_product_fit": ["cameras", "access_control", "guest"],
  "triggers_fired": ["incident_recent_12mo"],
  "risk_assessment": "one paragraph",
  "discovery_angle": "one sentence suggesting how an SE would open a conversation"
}}"""

    try:
        client = anthropic.Anthropic()
        msg = client.messages.create(
            model=HAIKU_MODEL,
            max_tokens=1500,
            messages=[{"role": "user", "content": prompt}],
        )
        text = msg.content[0].text
        json_match = re.search(r'\{.*\}', text, re.S)
        if json_match:
            return json.loads(json_match.group(0))
        return {"status": "parse_error", "raw": text[:500]}
    except Exception as e:
        return {"status": "extraction_error", "reason": str(e)}


# ---------------------------------------------------------------------------
# Cache management
# ---------------------------------------------------------------------------

def slugify(name: str) -> str:
    slug = name.lower().strip()
    slug = re.sub(r"[^a-z0-9]+", "-", slug)
    return slug.strip("-")


def cache_path(company_slug: str) -> Path:
    return SOURCES_DIR / company_slug / "hhs.json"


def read_cache(company_slug: str) -> dict | None:
    path = cache_path(company_slug)
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return None
    retrieved_at = data.get("retrieved_at")
    if not retrieved_at:
        return None
    try:
        ts = datetime.fromisoformat(retrieved_at)
    except ValueError:
        return None
    if datetime.now(timezone.utc) - ts > timedelta(days=CACHE_TTL_DAYS):
        return None
    return data


def write_cache(company_slug: str, data: dict) -> Path:
    path = cache_path(company_slug)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, default=str))
    print(f"  [cache] wrote {path}", file=sys.stderr)
    return path


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def fetch_hhs_data(entity_name: str, *, force_refresh: bool = False) -> dict:
    """Full pipeline: JSF navigate → parse table → filter entity → Haiku → cache."""
    company_slug = slugify(entity_name)

    if not force_refresh:
        cached = read_cache(company_slug)
        if cached is not None:
            return cached

    # Navigate JSF app
    print(f"  [hhs] navigating breach portal...", file=sys.stderr)
    session = _create_session()
    html = fetch_breach_page(session)

    if not html:
        result = {
            "retrieved_at": datetime.now(timezone.utc).isoformat(),
            "source": "hhs_ocr_breach",
            "source_url": "https://ocrportal.hhs.gov/ocr/breach/breach_report.jsf",
            "status": "insufficient_data",
            "reason": "Failed to navigate HHS OCR breach portal (JSF navigation failed)",
            "entity": {"name": entity_name},
        }
        write_cache(company_slug, result)
        return result

    # Parse all breach records from the page
    all_records = parse_breach_table(html)
    print(f"  [hhs] parsed {len(all_records)} breach records from portal", file=sys.stderr)

    # Filter for the target entity
    entity_records = filter_by_entity(all_records, entity_name)
    print(f"  [hhs] {len(entity_records)} records matching '{entity_name}'", file=sys.stderr)

    # Classify breach types
    breach_type_counts = {}
    total_affected = 0
    for rec in entity_records:
        bt = rec.get("breach_type", "Unknown")
        breach_type_counts[bt] = breach_type_counts.get(bt, 0) + 1
        total_affected += rec.get("individuals_affected", 0)

    # Haiku analysis
    persona = _load_persona()
    haiku_analysis = analyze_with_haiku(entity_records, entity_name, persona)

    result = {
        "retrieved_at": datetime.now(timezone.utc).isoformat(),
        "source": "hhs_ocr_breach",
        "source_url": "https://ocrportal.hhs.gov/ocr/breach/breach_report.jsf",
        "entity": {"name": entity_name},
        "portal_total_records": len(all_records),
        "entity_records": entity_records,
        "breach_type_counts": breach_type_counts,
        "haiku_analysis": haiku_analysis,
        "summary": {
            "entity_name": entity_name,
            "total_breaches": len(entity_records),
            "total_individuals_affected": total_affected,
            "breach_types": list(breach_type_counts.keys()),
            "most_recent_date": entity_records[0]["breach_submission_date"] if entity_records else None,
            "source_quality": "primary",
            "confidence": "high" if entity_records else "medium",
        },
    }

    if not entity_records:
        result["status"] = "no_matches"
        result["reason"] = (
            f"No breach records matching '{entity_name}' found in the most recent "
            f"{len(all_records)} records on the HHS OCR portal. The entity may have "
            f"no breaches affecting 500+ individuals, or records may be on later pages."
        )

    write_cache(company_slug, result)
    return result


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main():
    if len(sys.argv) < 2:
        print("Usage: python hhs.py <entity_name> [--force]", file=sys.stderr)
        print("  e.g.: python hhs.py 'Grady Health System'", file=sys.stderr)
        print("        python hhs.py 'Emory Healthcare' --force", file=sys.stderr)
        print("", file=sys.stderr)
        print("  No API key needed. Scrapes HHS OCR Breach Portal.", file=sys.stderr)
        sys.exit(1)

    entity_name = sys.argv[1]
    force = "--force" in sys.argv

    result = fetch_hhs_data(entity_name, force_refresh=force)

    summary = result.get("summary", {})
    if result.get("status") in ("insufficient_data", "no_matches"):
        print(f"\n  {result.get('reason', 'No data')}", file=sys.stderr)
    else:
        print(
            f"\n  Done: {summary.get('entity_name')}\n"
            f"  Total breaches: {summary.get('total_breaches', 0)}\n"
            f"  Individuals affected: {summary.get('total_individuals_affected', 0):,}\n"
            f"  Breach types: {summary.get('breach_types', [])}\n"
            f"  Most recent: {summary.get('most_recent_date', 'N/A')}\n"
            f"  Portal total records: {result.get('portal_total_records', 0)}\n"
            f"  Cached to: sources/{slugify(entity_name)}/hhs.json",
            file=sys.stderr,
        )

    print(json.dumps(result, indent=2, default=str))


if __name__ == "__main__":
    main()
